CREATE TABLE IF NOT EXISTS reminders (
  id SERIAL PRIMARY KEY,
  userid INTEGER REFERENCES "USER"(userid) ON DELETE SET NULL,
  title TEXT NOT NULL,
  date DATE NOT NULL,
  note TEXT,
  department VARCHAR(10) NOT NULL DEFAULT 'ALL',
  division VARCHAR(10) NOT NULL DEFAULT 'ALL'
);
